#!/usr/bin/env bash

__main__help='Usage:
 $ __app__ ${datadir__:-} ${task:-help}
'

__puton__ () {
  datadir__=${datadir__:-$HOME/.undies/leaves}
  pattern__mktemp=${pattern__mktemp:-'XXXX--%s.leave.md'}
  pattern__find=${pattern__find:-'*%s*.leave.md'}
  mkdir -p $datadir__
}

__fallback__ () {
  if [ -d $1 ]; then
    datadir__=$1
    shift
    __run "$@"
  else
    >&2 __help $@
  fi
}

here__ () {
  datadir__=$(pwd)
  mkdir -p $datadir__
  __run "$@"
}

__pattern () {
  local varname='pattern__'$1
  local title=$2
  printf ${!varname} $title
}

copy__help='@arg file @does copy file content into a new leaf'
copy__ () {
  local file=$1
  [ ! -e $file ] && return -1
  local title_default=$(basename $file)
  read -p "title? [$title_default] " title
  test -z $title && title=$title_default
  local test
  __prepare newfile $title
  echo '; copied from '$file >> $newfile
  cat $file >> $newfile
  __edit $newfile
}

__prepare () {
  local -n ref_newfile=$1
  local title=$2
  local pattern=$(__pattern mktemp $title)
  local mktemp_dir=$datadir__/$(dirname $pattern)
  local mktemp_tpl=$(basename $pattern)
  mkdir -p $mktemp_dir
  local mktemp_path=$(mktemp -p $mktemp_dir $mktemp_tpl)
  touch $mktemp_path
  echo 'created:' $(date) >> $mktemp_path
  echo '--' >> $mktemp_path
  read ${!ref_newfile} <<<$mktemp_path
}

new__ () {
  local title=$1
  test -z $title && read -p 'title? ' title
  __prepare newfile $title
  __edit $newfile
}

__edit () {
  __exec vim '+ normal Go' $1
}

list__ () {
  local title=${1:-''}
  set -o noglob
  find $datadir__ -wholename $(__pattern find $title) 2>/dev/null
}

edit__ () {
  local title=$1
  test -n $title || read -p 'title? ' title
  for leaf in $(list__ $title); do
    echo $leaf
    read -p 'edit [y|e,n,q,d,r]? ' -n1
    echo
    case $REPLY in
      d)
        __exec rm $leaf
	;;
      r)
        read -p $(basename $leaf)', rename? ' rename
	__exec mv $leaf $(dirname $leaf)/$rename
	;;
      y|e)
        __edit $leaf
	;;
      q)
        break
	;;
      n|*)
        continue
	;;
    esac
  done
  echo done
}

tree__help='@arg [pattern=*] [range=1,] @prints tree of leaves and their headlines @return null'
tree__ () {
  local pattern=${1:-'*'}
  local range=${2:-''}
  for leaf in $(list__ "$pattern"); do
    echo $leaf
    headings__ $leaf $range | sed 's|#|-|g'
  done
}

headings__help='@arg file @arg range=1, @prints list of heaings'
headings__ () {
  read leaf range <<< $@
  test ! -z $leaf && test -f $leaf || return -1
  range=${range:-'1,'}
  cat $leaf | grep -E "^[\#]{$range}[^\#].*$"
}

. undies
