#!/usr/bin/env bash

__puton__ () {
  datadir__=${datadir__:-$HOME/.undies/leaves}
  pattern__mktemp=${pattern__mktemp:-'XXXX--%s.leave.md'}
  pattern__find=${pattern__find:-'*%s*.leave.md'}
  mkdir -p $datadir__
}

here__ () {
  datadir__=$(pwd)
  mkdir -p $datadir__
  __run "$@"
}

__pattern () {
  local varname='pattern__'$1
  local title=$2
  printf ${!varname} $title
}

new__ () {
  local title=$1
  test -z $title && read -p 'title? ' title
  local pattern=$(__pattern mktemp $title)
  local mktemp_dir=$datadir__/$(dirname $pattern)
  local mktemp_tpl=$(basename $pattern)
  mkdir -p $mktemp_dir
  local new=$(mktemp -p $mktemp_dir $mktemp_tpl)
  touch $new
  echo 'created:' $(date) >> $new
  echo '--' >> $new
  __exec vim '+ normal Go' $new
}

list__ () {
  local title=${1:-''}
  set -o noglob
  find $datadir__ -wholename $(__pattern find $title)
}

edit__ () {
  local title=$1
  test -n $title || read -p 'title? ' title
  for leaf in $(list__ $title); do
    echo $leaf
    read -p 'edit [y|e,n,q,d,r]? ' -n1
    echo
    case $REPLY in
      d)
        __exec rm $leaf
	;;
      r)
        read -p $(basename $leaf)', rename? ' rename
	__exec mv $leaf $(dirname $leaf)/$rename
	;;
      y|e)
        vim '+ normal Go' $leaf
	;;
      q)
        break
	;;
      n|*)
        continue
	;;
    esac
  done
  echo done
}

tree__help='@arg [pattern=*] [range=1,] @prints tree of leaves and their headlines @return null'
tree__ () {
  local pattern=${1:-'*'}
  local range=${2:-''}
  for leaf in $(list__ "$pattern"); do
    echo $leaf
    headings__ $leaf $range | sed 's|#|-|g'
  done
}

headings__help='@arg file @arg range=1, @prints list of heaings'
headings__ () {
  read leaf range <<< $@
  test ! -z $leaf && test -f $leaf || return -1
  range=${range:-'1,'}
  cat $leaf | grep -E "^[\#]{$range}[^\#].*$"
}

. undies
